import { useEffect, useMemo, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, CheckCircle2, Clock } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { useTaskAlerts, useResolveAlert, useCreateAlert } from "@/hooks/useTaskAlerts";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { format } from "date-fns";

/**
 * 7-Day Confirmation pop-up shown to PMs.
 * Triggered by alerts of type `milestone_deadline` whose title contains
 * "Confirm construction end" — auto-generated by usePMDashboard when the
 * Construction End milestone is ≤7 days away.
 *
 * Flow:
 *  - "Confirm: work completed on schedule" → marks alert resolved + sets the
 *    related milestone to `achieved` with completed_date = today.
 *  - "Report delay / criticality" → opens textarea, marks original alert
 *    resolved and creates a new `pm_operational` alert (escalated to admin)
 *    with the PM's note. Date is NOT changed automatically.
 */
export function PMConfirmationDialog() {
  const { user, role } = useAuth();
  const qc = useQueryClient();
  const { alerts } = useTaskAlerts(role, user?.id) as any;
  const resolveAlert = useResolveAlert();
  const createAlert = useCreateAlert();

  const [dismissedIds, setDismissedIds] = useState<Set<string>>(new Set());
  const [reportMode, setReportMode] = useState<string | null>(null); // alert id
  const [delayNote, setDelayNote] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Only PMs see this dialog (admins see alerts in the inbox already)
  const isPM = role === "PM";

  const pendingConfirmations = useMemo(() => {
    if (!isPM || !alerts) return [];
    return (alerts as any[]).filter(
      (a) =>
        !a.is_resolved &&
        a.alert_type === "milestone_deadline" &&
        typeof a.title === "string" &&
        a.title.toLowerCase().includes("confirm construction end") &&
        !dismissedIds.has(a.id)
    );
  }, [alerts, isPM, dismissedIds]);

  const current = pendingConfirmations[0];
  const open = !!current;

  // Reset local state when current alert changes
  useEffect(() => {
    setReportMode(null);
    setDelayNote("");
  }, [current?.id]);

  if (!open || !current) return null;

  const handleConfirmCompleted = async () => {
    setSubmitting(true);
    try {
      const today = new Date().toISOString().slice(0, 10);

      // Find the matching Construction End milestone
      const { data: ms } = await (supabase as any)
        .from("certification_milestones")
        .select("id, requirement, status")
        .eq("certification_id", current.certification_id)
        .eq("milestone_type", "timeline");

      const target = (ms || []).find((m: any) => {
        const req = (m.requirement || "").toLowerCase().trim();
        return req === "construction end (handover)" || req === "construction end" || req === "handover";
      });

      if (target) {
        await (supabase as any)
          .from("certification_milestones")
          .update({ status: "achieved", completed_date: today, actual_date: today })
          .eq("id", target.id);
      }

      await resolveAlert.mutateAsync(current.id);
      qc.invalidateQueries({ queryKey: ["pm-dashboard"] });
      qc.invalidateQueries({ queryKey: ["admin-planner-all-certifications"] });
      qc.invalidateQueries({ queryKey: ["project-timeline"] });
      toast.success("Construction end confirmed");
    } catch (e: any) {
      toast.error(e?.message || "Failed to confirm");
    } finally {
      setSubmitting(false);
    }
  };

  const handleSubmitDelay = async () => {
    if (!delayNote.trim()) {
      toast.error("Please describe the delay / criticality");
      return;
    }
    if (!user?.id) return;
    setSubmitting(true);
    try {
      // Escalate to admin as pm_operational alert (no date change)
      await createAlert.mutateAsync({
        certification_id: current.certification_id,
        created_by: user.id,
        alert_type: "pm_operational",
        title: `Delay reported on ${current.certification_name || "project"}`,
        description: delayNote.trim(),
        escalate_to_admin: true,
      });
      await resolveAlert.mutateAsync(current.id);
      toast.success("Delay reported to admin");
    } catch (e: any) {
      toast.error(e?.message || "Failed to report");
    } finally {
      setSubmitting(false);
    }
  };

  const dueDateLabel = current.scheduled_date
    ? format(new Date(current.scheduled_date), "dd MMM yyyy")
    : "—";

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) {
          // Snooze for current session — alert remains in inbox
          setDismissedIds((prev) => new Set(prev).add(current.id));
        }
      }}
    >
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5 text-warning" />
            7-Day Confirmation Required
          </DialogTitle>
          <DialogDescription>
            Construction End is approaching for{" "}
            <span className="font-semibold text-foreground">{current.certification_name || "this project"}</span>.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <div className="flex items-center justify-between rounded-md border border-border bg-muted/30 p-3">
            <span className="text-sm text-muted-foreground">Planned Construction End</span>
            <Badge variant="outline" className="font-medium">{dueDateLabel}</Badge>
          </div>

          {reportMode === current.id ? (
            <div className="space-y-2">
              <label className="text-sm font-medium text-foreground">Describe the criticality</label>
              <Textarea
                value={delayNote}
                onChange={(e) => setDelayNote(e.target.value)}
                placeholder="e.g. Site delivery delayed by 2 weeks due to supplier issues..."
                rows={4}
                disabled={submitting}
              />
              <p className="text-xs text-muted-foreground">
                This will notify the Admin. The Construction End date will <strong>not</strong> be changed automatically — update it manually from the timeline once the new date is confirmed.
              </p>
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">
              Please confirm whether the works will be completed on schedule or report a criticality.
            </p>
          )}
        </div>

        <DialogFooter className="gap-2 sm:gap-2">
          {reportMode === current.id ? (
            <>
              <Button variant="outline" onClick={() => setReportMode(null)} disabled={submitting}>
                Back
              </Button>
              <Button variant="destructive" onClick={handleSubmitDelay} disabled={submitting}>
                <AlertTriangle className="mr-2 h-4 w-4" />
                Report to Admin
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" onClick={() => setReportMode(current.id)} disabled={submitting}>
                <AlertTriangle className="mr-2 h-4 w-4" />
                Report delay
              </Button>
              <Button onClick={handleConfirmCompleted} disabled={submitting}>
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Confirm completed
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
