-- Le scalette di milestone, caricate dai fogli di Sustainability_Project_Timelines.xlsx
-- piu' le quattro nuove per i servizi che si vendono da soli: Air, Energy,
-- Energy Audit e TAXONOMY. 242 passi su 22 scalette.
--
-- Generato da tl.py: le scadenze "Within N of X" diventano anchor_order +
-- offset_days, dove anchor_order e' il NUMERO della milestone da cui contare
-- dentro la stessa scaletta — per numero e non per nome, cosi' la regola
-- sopravvive a una rinominazione.
--
-- Dove il file dava una finestra ("6-8 months") si prende il bordo superiore:
-- e' la promessa verso il cliente. Una milestone obbligatoria non conta mai da
-- una opzionale: se il re-test non avviene, quella data non esiste mai.

INSERT INTO public.cert_timeline_steps (timeline_key, order_index, requirement, timing_kind, anchor_order, offset_days, optional) VALUES
('LEED ID+C', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('LEED ID+C', 2, 'FGB Design Guidelines', 'manual', NULL, NULL, false),
('LEED ID+C', 3, 'FGB Tendering Requirements', 'manual', NULL, NULL, false),
('LEED ID+C', 4, 'Construction Start', 'manual', NULL, NULL, false),
('LEED ID+C', 5, 'LEED GC Training', 'manual', NULL, NULL, false),
('LEED ID+C', 6, 'QlAir Shipment', 'manual', NULL, NULL, true),
('LEED ID+C', 7, 'Greeny Shipment', 'manual', NULL, NULL, true),
('LEED ID+C', 8, 'Commissioning tests and reports', 'manual', NULL, NULL, false),
('LEED ID+C', 9, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('LEED ID+C', 10, 'GC Provides Closed-out Documentation', 'calculated', 9, 30, false),
('LEED ID+C', 11, 'LEED Project Submission', 'calculated', 9, 60, false),
('LEED ID+C', 12, 'LEED Certification Attainment', 'calculated', 9, 150, false),
('LEED BD+C', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('LEED BD+C', 2, 'FGB Design Guidelines', 'manual', NULL, NULL, false),
('LEED BD+C', 3, 'FGB Tendering Requirements', 'manual', NULL, NULL, false),
('LEED BD+C', 4, 'Construction Start', 'manual', NULL, NULL, false),
('LEED BD+C', 5, 'LEED GC Training', 'manual', NULL, NULL, false),
('LEED BD+C', 6, 'QlAir Shipment', 'manual', NULL, NULL, true),
('LEED BD+C', 7, 'Greeny Shipment', 'manual', NULL, NULL, true),
('LEED BD+C', 8, 'Commissioning tests and reports', 'manual', NULL, NULL, false),
('LEED BD+C', 9, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('LEED BD+C', 10, 'GC Provides Closed-out Documentation', 'calculated', 9, 30, false),
('LEED BD+C', 11, 'CxA site inspection and tests', 'calculated', 9, 60, false),
('LEED BD+C', 12, 'LEED Project Submission', 'calculated', 9, 90, false),
('LEED BD+C', 13, 'LEED Certification Attainment', 'calculated', 9, 180, false),
('LEED O+M', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('LEED O+M', 2, 'Completed documentation received', 'manual', NULL, NULL, false),
('LEED O+M', 3, 'On-site Visit and QlAir installation', 'manual', NULL, NULL, false),
('LEED O+M', 4, '12 months Performance Period End', 'manual', NULL, NULL, false),
('LEED O+M', 5, 'LEED Project Submission', 'calculated', 4, 30, false),
('LEED O+M', 6, 'LEED Certification Attainment', 'calculated', 4, 120, false),
('BREEAM NC / RFO', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 2, 'FGB Design Guidelines', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 3, 'FGB Tendering Requirements', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 4, 'Construction Start', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 5, 'BREEAM GC Training', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 6, 'QlAir Shipment', 'manual', NULL, NULL, true),
('BREEAM NC / RFO', 7, 'Greeny Shipment', 'manual', NULL, NULL, true),
('BREEAM NC / RFO', 8, 'Commissioning tests and reports', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 9, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('BREEAM NC / RFO', 10, 'GC Provides Closed-out Documentation', 'calculated', 9, 30, false),
('BREEAM NC / RFO', 11, 'CxA site inspection and tests', 'calculated', 9, 60, false),
('BREEAM NC / RFO', 12, 'BREEAM Assessor Site Visit', 'calculated', 9, 60, false),
('BREEAM NC / RFO', 13, 'BREEAM Assessment Submission', 'calculated', 9, 90, false),
('BREEAM NC / RFO', 14, 'BREEAM Certification Attainment', 'calculated', 9, 240, false),
('BREEAM In-Use Part 1', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 1', 2, 'FGB Sustainability Guidelines', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 1', 3, 'Completed documentation received', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 1', 4, 'Implementation activities start', 'manual', NULL, NULL, true),
('BREEAM In-Use Part 1', 5, 'Implementation activities end', 'manual', NULL, NULL, true),
('BREEAM In-Use Part 1', 6, 'BREEAM Assessor Site Visit', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 1', 7, 'BREEAM Assessment Submission', 'calculated', 6, 30, false),
('BREEAM In-Use Part 1', 8, 'BREEAM Certification Attainment', 'calculated', 6, 180, false),
('BREEAM In-Use Part 2', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 2', 2, 'FGB Sustainability Guidelines', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 2', 3, 'Completed documentation received', 'manual', NULL, NULL, false),
('BREEAM In-Use Part 2', 4, 'BREEAM Assessment Submission', 'calculated', 3, 30, false),
('BREEAM In-Use Part 2', 5, 'BREEAM Certification Attainment', 'calculated', 3, 180, false),
('WELL New Construction', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('WELL New Construction', 2, 'FGB Sustainability Guidelines', 'manual', NULL, NULL, false),
('WELL New Construction', 3, 'FGB Tendering Requirements', 'manual', NULL, NULL, false),
('WELL New Construction', 4, 'Construction Phase Start', 'manual', NULL, NULL, false),
('WELL New Construction', 5, 'WELL GC Training', 'manual', NULL, NULL, false),
('WELL New Construction', 6, 'QlAir Installation', 'manual', NULL, NULL, true),
('WELL New Construction', 7, 'Commissioning tests and reports', 'manual', NULL, NULL, false),
('WELL New Construction', 8, 'WELL Performance Verification Pre-Test', 'manual', NULL, NULL, true),
('WELL New Construction', 9, 'WELL Performance Verification Pre-Test Results', 'calculated', 8, 30, true),
('WELL New Construction', 10, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('WELL New Construction', 11, 'GC Provides Closed-out Documentation', 'calculated', 10, 30, false),
('WELL New Construction', 12, 'Client Provides Policies and Operational Schedules', 'manual', NULL, NULL, false),
('WELL New Construction', 13, 'CxA Activities and WELL Performance Verification', 'manual', NULL, NULL, false),
('WELL New Construction', 14, 'WELL Performance Verification Results', 'calculated', 13, 30, false),
('WELL New Construction', 15, 'Corrective Actions Completed (if needed)', 'manual', NULL, NULL, true),
('WELL New Construction', 16, 'WELL Performance Verification Re-testing (if needed)', 'manual', NULL, NULL, true),
('WELL New Construction', 17, 'Final WELL Performance Verification Results (if needed)', 'calculated', 16, 7, true),
('WELL New Construction', 18, 'WELL Project Submission', 'calculated', 14, 60, false),
('WELL New Construction', 19, 'WELL Certification Attainment', 'calculated', 14, 180, false),
('WELL Existing Building', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('WELL Existing Building', 2, 'FGB Sustainability Guidelines', 'manual', NULL, NULL, false),
('WELL Existing Building', 3, 'QlAir Installation', 'manual', NULL, NULL, true),
('WELL Existing Building', 4, 'Client Provides Policies and Completed Documentation', 'manual', NULL, NULL, false),
('WELL Existing Building', 5, 'WELL Performance Verification', 'manual', NULL, NULL, false),
('WELL Existing Building', 6, 'WELL Performance Verification Results', 'calculated', 5, 30, false),
('WELL Existing Building', 7, 'Corrective Actions Completed (if needed)', 'manual', NULL, NULL, true),
('WELL Existing Building', 8, 'WELL Performance Verification Re-testing (if needed)', 'manual', NULL, NULL, true),
('WELL Existing Building', 9, 'Final WELL Performance Verification Results (if needed)', 'calculated', 8, 7, true),
('WELL Existing Building', 10, 'WELL Project Submission', 'calculated', 6, 60, false),
('WELL Existing Building', 11, 'WELL Certification Attainment', 'calculated', 6, 180, false),
('WELL Core', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('WELL Core', 2, 'FGB Sustainability Guidelines', 'manual', NULL, NULL, false),
('WELL Core', 3, 'FGB Tendering Requirements', 'manual', NULL, NULL, false),
('WELL Core', 4, 'Construction Phase Start', 'manual', NULL, NULL, false),
('WELL Core', 5, 'WELL GC Training', 'manual', NULL, NULL, false),
('WELL Core', 6, 'QlAir Installation', 'manual', NULL, NULL, true),
('WELL Core', 7, 'Commissioning tests and reports', 'manual', NULL, NULL, false),
('WELL Core', 8, 'WELL Performance Verification Pre-Test', 'manual', NULL, NULL, true),
('WELL Core', 9, 'WELL Performance Verification Pre-Test Results', 'calculated', 8, 30, true),
('WELL Core', 10, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('WELL Core', 11, 'GC Provides Closed-out Documentation', 'calculated', 10, 30, false),
('WELL Core', 12, 'Client Provides Policies and Operational Schedules', 'manual', NULL, NULL, false),
('WELL Core', 13, 'CxA Activities and WELL Performance Verification', 'manual', NULL, NULL, false),
('WELL Core', 14, 'WELL Performance Verification Results', 'calculated', 13, 30, false),
('WELL Core', 15, 'Corrective Actions Completed (if needed)', 'manual', NULL, NULL, true),
('WELL Core', 16, 'WELL Performance Verification Re-testing (if needed)', 'manual', NULL, NULL, true),
('WELL Core', 17, 'Final WELL Performance Verification Results (if needed)', 'calculated', 16, 7, true),
('WELL Core', 18, 'WELL Project Submission', 'calculated', 14, 60, false),
('WELL Core', 19, 'WELL Certification Attainment', 'calculated', 14, 180, false),
('MEP Commissioning', 1, 'Commissioning Kick-off', 'manual', NULL, NULL, false),
('MEP Commissioning', 2, 'Commissioning Plan Issued', 'manual', NULL, NULL, false),
('MEP Commissioning', 3, 'Commissioning Design Review', 'manual', NULL, NULL, false),
('MEP Commissioning', 4, 'Construction Start', 'manual', NULL, NULL, false),
('MEP Commissioning', 5, 'Systems Ready for Testing', 'manual', NULL, NULL, false),
('MEP Commissioning', 6, 'Functional Performance Testing', 'manual', NULL, NULL, false),
('MEP Commissioning', 7, 'Commissioning Issues Closed', 'manual', NULL, NULL, true),
('MEP Commissioning', 8, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('MEP Commissioning', 9, 'GC Provides Closed-out Commissioning Documentation', 'calculated', 8, 30, false),
('MEP Commissioning', 10, 'CxA site inspection and tests', 'calculated', 8, 60, false),
('MEP Commissioning', 11, 'Final Commissioning Report Issued', 'calculated', 10, 30, false),
('Envelope Commissioning', 1, 'Envelope Commissioning Kick-off', 'manual', NULL, NULL, false),
('Envelope Commissioning', 2, 'Commissioning Plan Issued', 'manual', NULL, NULL, false),
('Envelope Commissioning', 3, 'Envelope Design Review', 'manual', NULL, NULL, false),
('Envelope Commissioning', 4, 'Construction Start', 'manual', NULL, NULL, false),
('Envelope Commissioning', 5, 'Envelope Site Inspection & On-site Testing', 'manual', NULL, NULL, false),
('Envelope Commissioning', 6, 'Envelope Issues Closed', 'manual', NULL, NULL, true),
('Envelope Commissioning', 7, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('Envelope Commissioning', 8, 'GC Provides Closed-out Commissioning Documentation', 'calculated', 7, 30, false),
('Envelope Commissioning', 9, 'CxA site inspection and tests', 'calculated', 7, 60, false),
('Envelope Commissioning', 10, 'Final Envelope Commissioning Report Issued', 'calculated', 9, 30, false),
('IAQ Testing', 1, 'IAQ Testing Plan Issued', 'manual', NULL, NULL, false),
('IAQ Testing', 2, 'Site Ready for IAQ Testing', 'manual', NULL, NULL, false),
('IAQ Testing', 3, 'On-site IAQ Testing', 'manual', NULL, NULL, false),
('IAQ Testing', 4, 'IAQ Testing Report Issued', 'calculated', 3, 30, false),
('IAQ Testing', 5, 'Corrective Actions Completed (if needed)', 'manual', NULL, NULL, true),
('IAQ Testing', 6, 'IAQ Re-testing (if needed)', 'manual', NULL, NULL, true),
('IAQ Testing', 7, 'Final IAQ Testing Report Issued (if needed)', 'calculated', 6, 30, true),
('IAQ Testing', 8, 'Preliminary IAQ Testing submission', 'calculated', 4, 7, false),
('IAQ Testing', 9, 'Final IAQ Testing Submission', 'manual', NULL, NULL, false),
('WELL PTA', 1, 'WELL Performance Testing Kick-off', 'manual', NULL, NULL, false),
('WELL PTA', 2, 'Testing Scope and Plan Issued', 'manual', NULL, NULL, false),
('WELL PTA', 3, 'Construction Start', 'manual', NULL, NULL, false),
('WELL PTA', 4, 'Site Inspection and Testing Points Defined', 'manual', NULL, NULL, false),
('WELL PTA', 5, 'Site Ready for WELL Performance Testing', 'manual', NULL, NULL, false),
('WELL PTA', 6, 'QlAir Installation', 'manual', NULL, NULL, true),
('WELL PTA', 7, 'WELL Performance Testing', 'manual', NULL, NULL, false),
('WELL PTA', 8, 'WELL Performance Testing Results Issued', 'calculated', 7, 30, false),
('WELL PTA', 9, 'Corrective Actions Completed (if needed)', 'manual', NULL, NULL, true),
('WELL PTA', 10, 'WELL Performance Re-testing (if needed)', 'manual', NULL, NULL, true),
('WELL PTA', 11, 'Final WELL Performance Testing Results Issued (if needed)', 'calculated', 10, 30, true),
('WELL PTA', 12, 'Preliminary WELL Performance Testing Submission', 'calculated', 8, 14, false),
('WELL PTA', 13, 'Final WELL Performance Testing Submission', 'manual', NULL, NULL, false),
('LEED GC Support', 1, 'LEED GC Support Kick-off', 'manual', NULL, NULL, true),
('LEED GC Support', 2, 'Construction Start', 'manual', NULL, NULL, false),
('LEED GC Support', 3, 'LEED GC Training', 'manual', NULL, NULL, false),
('LEED GC Support', 4, 'FGB Construction Report No. 1 Issued', 'manual', NULL, NULL, true),
('LEED GC Support', 5, 'FGB Construction Report No. 2 Issued', 'manual', NULL, NULL, true),
('LEED GC Support', 6, 'FGB Construction Report No. 3 Issued', 'manual', NULL, NULL, true),
('LEED GC Support', 7, '…', 'manual', NULL, NULL, true),
('LEED GC Support', 8, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('LEED GC Support', 9, 'GC Provides Closed-out Documentation', 'calculated', 8, 30, false),
('LEED GC Support', 10, 'Preliminary Construction Credits Completed', 'calculated', 8, 14, false),
('LEED GC Support', 11, 'Final Construction Credits Completed', 'manual', NULL, NULL, true),
('BREEAM GC Support', 1, 'BREEAM GC Support Kick-off', 'manual', NULL, NULL, true),
('BREEAM GC Support', 2, 'Construction Start', 'manual', NULL, NULL, false),
('BREEAM GC Support', 3, 'BREEAM GC Training', 'manual', NULL, NULL, false),
('BREEAM GC Support', 4, 'FGB Construction Report No. 1 Issued', 'manual', NULL, NULL, true),
('BREEAM GC Support', 5, 'FGB Construction Report No. 2 Issued', 'manual', NULL, NULL, true),
('BREEAM GC Support', 6, 'FGB Construction Report No. 3 Issued', 'manual', NULL, NULL, true),
('BREEAM GC Support', 7, '…', 'manual', NULL, NULL, true),
('BREEAM GC Support', 8, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('BREEAM GC Support', 9, 'GC Provides Closed-out Documentation', 'calculated', 8, 30, false),
('BREEAM GC Support', 10, 'Preliminary Construction Credits Completed', 'calculated', 8, 14, false),
('BREEAM GC Support', 11, 'Final Construction Credits Completed', 'manual', NULL, NULL, true),
('WELL GC Support', 1, 'WELL GC Support Kick-off', 'manual', NULL, NULL, true),
('WELL GC Support', 2, 'Construction Start', 'manual', NULL, NULL, false),
('WELL GC Support', 3, 'WELL GC Training', 'manual', NULL, NULL, false),
('WELL GC Support', 4, 'FGB Construction Report No. 1 Issued', 'manual', NULL, NULL, true),
('WELL GC Support', 5, 'FGB Construction Report No. 2 Issued', 'manual', NULL, NULL, true),
('WELL GC Support', 6, 'FGB Construction Report No. 3 Issued', 'manual', NULL, NULL, true),
('WELL GC Support', 7, '…', 'manual', NULL, NULL, true),
('WELL GC Support', 8, 'WELL Performance Verification Pre-Test', 'manual', NULL, NULL, true),
('WELL GC Support', 9, 'WELL Performance Verification Pre-Test Results', 'calculated', 8, 30, true),
('WELL GC Support', 10, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('WELL GC Support', 11, 'GC Provides Closed-out Documentation', 'calculated', 10, 30, false),
('WELL GC Support', 12, 'Preliminary Construction Credits Completed', 'manual', NULL, NULL, false),
('WELL GC Support', 13, 'Final Construction Credits Completed', 'manual', NULL, NULL, false),
('WiredScore Dev', 1, 'Pre-assessment & Strategy (Target Level Definition)', 'manual', NULL, NULL, false),
('WiredScore Dev', 2, 'FGB Connectivity/Telecom Design Guidelines', 'manual', NULL, NULL, false),
('WiredScore Dev', 3, 'WiredScore Design Phase Submission (Pre-Certification)', 'manual', NULL, NULL, false),
('WiredScore Dev', 4, 'Pre-certified Attainment', 'calculated', 3, 30, false),
('WiredScore Dev', 5, 'Tendering Requirements (Telecom/IT packages)', 'manual', NULL, NULL, false),
('WiredScore Dev', 6, 'Construction Start', 'manual', NULL, NULL, false),
('WiredScore Dev', 7, 'GC / MEP Contractor Training', 'manual', NULL, NULL, false),
('WiredScore Dev', 8, 'Construction End (Handover)', 'manual', NULL, NULL, false),
('WiredScore Dev', 9, 'GC Provides As-Built Documentation (Telecom)', 'calculated', 8, 30, false),
('WiredScore Dev', 10, 'WiredScore Auditor Site Visit', 'calculated', 8, 60, false),
('WiredScore Dev', 11, 'Final WiredScore Project Submission', 'calculated', 8, 60, false),
('WiredScore Dev', 12, 'WiredScore Certification Attainment', 'calculated', 8, 120, false),
('WiredScore Occ', 1, 'Pre-assessment', 'manual', NULL, NULL, false),
('WiredScore Occ', 2, 'Completed ISP/Telecom documentation received', 'manual', NULL, NULL, false),
('WiredScore Occ', 3, 'WiredScore Auditor Site Visit', 'manual', NULL, NULL, false),
('WiredScore Occ', 4, 'Gap Analysis & Remediation Plan (se necessario per l''upgrade)', 'calculated', 3, 30, true),
('WiredScore Occ', 5, 'Implementation of Corrective Actions (es. nuovi cablaggi)', 'manual', NULL, NULL, true),
('WiredScore Occ', 6, 'WiredScore Assessment Submission', 'calculated', 2, 30, false),
('WiredScore Occ', 7, 'WiredScore Certification Attainment', 'calculated', 6, 90, false);
